# Generated by Django 2.1 on 2019-05-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('A', 'Client User'), ('B', 'Customer User')], default='B', max_length=1)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(choices=[('C', 'その他'), ('A', '男性'), ('B', '女性')], default=None, max_length=1, null=True)),
                ('birth_year', models.IntegerField(default=None, max_length=4, null=True)),
                ('birth_month', models.IntegerField(default=None, max_length=2, null=True)),
                ('birth_day', models.IntegerField(default=None, max_length=2, null=True)),
                ('address', models.CharField(default=None, max_length=300, null=True)),
                ('phone', models.IntegerField(default=None, max_length=12, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=4)),
                ('published', models.DateField()),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='カテゴリ'),
        ),
    ]
