# Generated by Django 2.1 on 2019-06-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('B', 'Customer User'), ('A', 'Client User')], default='B', max_length=1)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(choices=[('A', '男性'), ('B', '女性'), ('C', 'その他')], default=None, max_length=1, null=True)),
                ('birth_year', models.IntegerField(default=None, max_length=4, null=True)),
                ('birth_month', models.IntegerField(default=None, max_length=2, null=True)),
                ('birth_day', models.IntegerField(default=None, max_length=2, null=True)),
                ('address', models.CharField(default=None, max_length=300, null=True)),
                ('phone', models.IntegerField(default=None, max_length=12, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=4)),
                ('published', models.DateField()),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Company_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pr', models.CharField(max_length=70)),
                ('tell', models.CharField(max_length=12)),
                ('price', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('credit', models.CharField(max_length=50)),
                ('homepage', models.URLField(max_length=100)),
                ('staff', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('service', models.TextField()),
                ('pay', models.TextField()),
                ('cancel', models.TextField()),
                ('security', models.TextField()),
                ('place1', models.CharField(max_length=10)),
                ('place2', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'company_data',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_plan', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=75)),
                ('price', models.CharField(max_length=30)),
                ('terms', models.CharField(max_length=20)),
                ('effect', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='company_data',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Genre', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='カテゴリ'),
        ),
    ]
