# Generated by Django 2.1 on 2019-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('B', '女性'), ('C', 'その他'), ('A', '男性')], default=None, max_length=1, null=True),
        ),
    ]
