# Generated by Django 2.1 on 2019-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pr', models.CharField(max_length=70)),
                ('tell', models.CharField(max_length=12)),
                ('price', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('credit', models.CharField(max_length=50)),
                ('homepage', models.URLField(max_length=100)),
                ('staff', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('service', models.TextField()),
                ('pay', models.TextField()),
                ('cancel', models.TextField()),
                ('security', models.TextField()),
            ],
            options={
                'db_table': 'company_data',
            },
        ),
    ]
