# Generated by Django 2.1 on 2019-05-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Client User'), ('B', 'Customer User')], default='B', max_length=1),
        ),
    ]
