# Generated by Django 2.1 on 2019-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_plan', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=75)),
                ('price', models.CharField(max_length=30)),
                ('terms', models.CharField(max_length=20)),
                ('effect', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
