# Generated by Django 2.1 on 2019-05-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190526_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinds', models.CharField(choices=[('C', 'ご利用方法について'), ('B', '会員情報について'), ('D', 'その他'), ('A', 'ご注文について')], default='C', max_length=1)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('message', models.CharField(max_length=300)),
                ('phone', models.TextField(max_length=12)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('A', '男性'), ('B', '女性'), ('C', 'その他')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Client User'), ('B', 'Customer User')], default='B', max_length=1),
        ),
    ]
