# Generated by Django 2.1 on 2019-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190526_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('B', '女性'), ('C', 'その他'), ('A', '男性')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('B', 'Customer User'), ('A', 'Client User')], default='B', max_length=1),
        ),
    ]
