# Generated by Django 2.1 on 2019-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190526_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('A', '男性'), ('C', 'その他'), ('B', '女性')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Client User'), ('B', 'Customer User')], default='B', max_length=1),
        ),
    ]
