# Generated by Django 2.1 on 2019-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190528_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('A', '男性'), ('C', 'その他'), ('B', '女性')], default=None, max_length=1, null=True),
        ),
    ]
