# Generated by Django 2.1 on 2019-05-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190526_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('C', 'その他'), ('A', '男性'), ('B', '女性')], default=None, max_length=1, null=True),
        ),
    ]
