# Generated by Django 2.1 on 2019-05-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190529_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('C', 'その他'), ('B', '女性'), ('A', '男性')], default=None, max_length=1, null=True),
        ),
    ]
