# Generated by Django 2.1 on 2019-05-30 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190530_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chat',
            name='foo',
            field=models.IntegerField(choices=[(1, 'ご注文について'), (2, '会員情報について'), (3, 'ご利用方法について'), (4, 'その他')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('B', '女性'), ('C', 'その他'), ('A', '男性')], default=None, max_length=1, null=True),
        ),
    ]
