# Generated by Django 2.1 on 2019-05-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190530_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=128)),
                ('message', models.CharField(max_length=300)),
                ('phone', models.TextField(max_length=12)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('C', 'その他'), ('A', '男性'), ('B', '女性')], default=None, max_length=1, null=True),
        ),
    ]
