# Generated by Django 2.1 on 2019-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190530_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='foo',
            field=models.IntegerField(choices=[(1, 'ご注文について'), (2, '会員情報について'), (3, 'ご利用方法について'), (4, '掲載資料請求について'), (5, 'その他')]),
        ),
    ]
