# Generated by Django 2.1 on 2019-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190526_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_data',
            name='place1',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_data',
            name='place2',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('B', '女性'), ('C', 'その他'), ('A', '男性')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Client User'), ('B', 'Customer User')], default='B', max_length=1),
        ),
    ]
